name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  java-ci-checks:
    name: Automated Java CI checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify